// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
)

type StockTicker struct {
	TickerID      uuid.UUID
	CompanyName   string
	Ticker        string
	Favorited     bool
	Tags          pqtype.NullRawMessage
	AddedDateTime time.Time
}
